name: Build

on:
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2025
    environment: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install JOM
      run: |
        curl http://download.qt.io/official_releases/jom/jom.zip -L --output jom.zip
        Expand-Archive -DestinationPath C:\jom jom.zip
        echo C:\jom >> $env:GITHUB_PATH

    - name: JOM Test
      run: |
        dir C:\jom
        echo $env:PATH
        jom /?

    - name: Install QT
      run: |
        curl https://download.qt.io/official_releases/online_installers/qt-online-installer-windows-x64-online.exe -L --output qt-online-installer-windows-x64-online.exe
        $env:QT_INSTALLER_JWT_TOKEN="${{ secrets.QT_INSTALLER_JWT_TOKEN }}"
        .\qt-online-installer-windows-x64-online.exe --root C:\Qt --auto-answer telemetry-question=No --accept-licenses --accept-obligations --confirm-command install qt6-msvc2022-essentials-dev

        $qt_root = Resolve-Path C:\Qt\*\msvc2022_64
        echo QT_ROOT=$qt_root >> $env:GITHUB_ENV
        echo "$qt_root\bin" >> $env:GITHUB_PATH

    - name: QT Test
      run: |
        echo $env:QT_ROOT
        qmake --help
        
    - name: Generate
      run: qmake
    - name: Build
      run: jom

    - name: Create Distribution
      run: |
        mkdir dist
        copy kernel.cl dist
        copy release\*.exe dist
        copy libraries\Windows\*.dll dist
        copy "${env:QT_ROOT}\bin\*.dll" dist

        mkdir dist\platforms
        copy "${env:QT_ROOT}\plugins\platforms\*.dll" dist\platforms
  
    - name: Upload Distribution
      uses: actions/upload-artifact@v4
      with:
        name: windows-dist
        path: dist
